export const todoURL = 'https://demo.playwright.dev/todomvc/#/';
export const todoInput = '.new-todo';
export const inputText = '[data-testid="todo-title"]';
export const todoList = '.todo-list';
export const todoItem = '[data-testid="todo-item"]';
export const deleteButton = '[aria-label="Delete"]';
export const completeTaskCheckbox = '[aria-label="Toggle Todo"]';
export const clearCompletedTasksButton = '.clear-completed';
export const editIem = '.edit';
export const filters = '.filters';
export const placeholderText = 'What needs to be done?';
export const headerText = 'todos';
